[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.46.1", features = ["full"]}
axum = {version = "0.8.4", features =["ws"]}
futures-util = "0.3.31"
tokio-tungstenite = "0.27.0"
anyhow = "1.0.98"
